"""
evaluate_stories.py
-------------------
This is the DATA SCIENCE part of our project.

We take 5 real stories generated by our app and measure:
1. Flesch-Kincaid Grade Level  -- what school grade can read this?
2. Reading Ease Score          -- how easy is it to read? (0-100, higher = easier)
3. Word Count                  -- how long is the story?
4. Avg Sentence Length         -- shorter = better for kids
5. Age Appropriateness         -- does the reading level match the target age?

This is what separates an AI/DS project from a software project.
We are EVALUATING our model output with real metrics.

Run with: venv\Scripts\python evaluate_stories.py
"""

import textstat
import json

# ── Sample stories generated by our app (Groq Llama 3.3 70B) ─────────────────
# These are real outputs from our system, one per age group

STORIES = [
    {
        "title": "Ali and the Forbidden Cave",
        "target_age": 6,
        "gender": "boy",
        "theme": "adventure",
        "text": """
        Ali lived in a small village near a big forest. One sunny morning, he saw a dark cave
        behind the old oak tree. A sign said Do Not Enter, but Ali was curious. He thought,
        just a quick look will not hurt anyone. He went inside. The cave was cold and dark.
        Ali slipped on a wet rock and fell down. He hurt his knee and could not find the way out.
        He sat in the dark and felt very scared. Then he heard his mother calling his name.
        She had seen him go in. She helped him out and held his hand tight. Ali said sorry and
        promised to always read the signs. His knee hurt for a week, but he never forgot that day.
        """
    },
    {
        "title": "Sara and the Baby Bird",
        "target_age": 7,
        "gender": "girl",
        "theme": "animals",
        "text": """
        Sara found a tiny bird with a broken wing near the garden wall. She picked it up gently
        and carried it home in her warm hands. She wanted to keep it forever as her pet. She made
        a little box with soft cotton and fed it bread crumbs every morning. But the bird looked
        sad. It kept trying to flap its wings and fly to the window. One day her father said,
        Sara, wild birds need the sky, not a box. Sara felt a pain in her chest. She did not want
        to let go. But she opened the window anyway. The bird sat on her finger for one moment,
        looked at her with its tiny black eyes, and flew away into the blue sky. Sara cried a
        little. But she also smiled, because she knew she had done the right thing.
        """
    },
    {
        "title": "Omar and the Magic Lamp",
        "target_age": 9,
        "gender": "boy",
        "theme": "fantasy",
        "text": """
        Omar discovered an old brass lamp buried under the sand dunes behind his house. When he
        rubbed it, a genie appeared in a swirl of golden smoke. The genie said he had one wish,
        just one, so choose carefully. Omar immediately thought of all the things he wanted.
        A new bicycle, a big house, all the sweets in the world. But then he remembered his
        grandmother who was sick in the hospital. He closed his eyes and wished for her to be
        healthy again. The genie looked surprised. Most people wish for themselves, he said quietly.
        Omar shrugged and said, what is the point of a bicycle if she cannot see me ride it?
        The next morning his grandmother walked into the kitchen and made breakfast. Omar never
        told anyone about the lamp. He did not need to.
        """
    },
    {
        "title": "Zara and the Coral Reef",
        "target_age": 8,
        "gender": "girl",
        "theme": "ocean",
        "text": """
        Zara loved swimming more than anything in the world. Every day she swam near the shore,
        but she always stared at the distant coral reef where the water turned deep blue. The old
        fisherman warned her never to swim there because of the strong current. One afternoon,
        when no one was watching, Zara swam toward the reef. The colors were beautiful, orange
        and purple fish darted between the coral. But then the current grabbed her legs and pulled
        her sideways. She kicked hard but could not move forward. She was getting tired. She
        remembered the fisherman's words and stopped fighting the current. She swam sideways
        instead, just like he had taught her once. Slowly she reached the shallow water and
        collapsed on the sand, breathing hard. The fisherman was standing there. He did not say
        I told you so. He just handed her a towel.
        """
    },
    {
        "title": "Hamza and the Shooting Star",
        "target_age": 10,
        "gender": "boy",
        "theme": "space",
        "text": """
        Hamza was the youngest crew member on the research shuttle Orion. During a routine mission
        near Jupiter, the ship's sensors detected an unusual signal from a small asteroid. The
        captain said to ignore it and stay on course. But Hamza was convinced it was a distress
        beacon from a lost probe. He secretly adjusted the navigation by two degrees. The captain
        noticed immediately and was furious. Hamza, you do not change course without authorization,
        she said. But as they argued, the signal grew stronger. They found the probe, and inside
        its memory banks were three years of climate data from Jupiter's moons, data that scientists
        on Earth had been waiting for. The captain looked at Hamza for a long moment. You were right,
        she said. But next time you ask first. Hamza nodded. He had learned that being right and
        being responsible were two different things.
        """
    },
]


def analyze(text: str, target_age: int) -> dict:
    """Calculate readability metrics for a story."""
    clean = " ".join(text.split())  # normalize whitespace

    grade  = textstat.flesch_kincaid_grade(clean)
    ease   = textstat.flesch_reading_ease(clean)
    words  = textstat.lexicon_count(clean)
    sents  = textstat.sentence_count(clean)
    avg_sl = round(words / sents, 1) if sents > 0 else 0

    # Age appropriateness: FK grade should roughly match age/2
    # e.g. age 6 -> grade ~3, age 10 -> grade ~5
    expected_grade = target_age / 2
    appropriate = abs(grade - expected_grade) <= 1.5

    return {
        "fk_grade":    round(grade, 1),
        "ease_score":  round(ease, 1),
        "word_count":  words,
        "sentences":   sents,
        "avg_sent_len": avg_sl,
        "age_appropriate": appropriate,
    }


# ── Run evaluation ────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("  KIDS STORY GENERATOR — AI/DS EVALUATION REPORT")
print("  Model: Groq Llama 3.3 70B | Metric: Flesch-Kincaid Readability")
print("=" * 70)

print(f"\n{'Title':<35} {'Age':>4} {'FK Grade':>9} {'Ease':>6} {'Words':>6} {'Appropriate':>12}")
print("-" * 70)

results = []
for story in STORIES:
    m = analyze(story["text"], story["target_age"])
    results.append(m)
    flag = "YES" if m["age_appropriate"] else "NO"
    print(f"{story['title']:<35} {story['target_age']:>4} {m['fk_grade']:>9} "
          f"{m['ease_score']:>6} {m['word_count']:>6} {flag:>12}")

# ── Summary stats ─────────────────────────────────────────────────────────────
avg_grade = sum(r["fk_grade"]  for r in results) / len(results)
avg_ease  = sum(r["ease_score"] for r in results) / len(results)
avg_words = sum(r["word_count"] for r in results) / len(results)
pct_ok    = sum(1 for r in results if r["age_appropriate"]) / len(results) * 100

print("-" * 70)
print(f"\nSUMMARY ACROSS {len(STORIES)} STORIES:")
print(f"  Avg Flesch-Kincaid Grade:  {avg_grade:.1f}  (target: ~4-5 for ages 6-10)")
print(f"  Avg Reading Ease Score:    {avg_ease:.1f}  (60-70 = standard, 70-80 = easy)")
print(f"  Avg Word Count per Story:  {avg_words:.0f} words")
print(f"  Age-Appropriate Stories:   {pct_ok:.0f}%")

print("\nREADABILITY SCALE (Flesch Reading Ease):")
print("  90-100 = Very Easy (age 5)")
print("  70-80  = Easy (age 6-8)")
print("  60-70  = Standard (age 9-12)")
print("  50-60  = Fairly Difficult (adult)")

print("\nCONCLUSION:")
if pct_ok >= 80:
    print(f"  {pct_ok:.0f}% of generated stories are age-appropriate.")
    print("  The system successfully adapts language complexity to the target age.")
else:
    print(f"  Only {pct_ok:.0f}% of stories matched the target age level.")
    print("  Prompt engineering improvements needed for better age calibration.")

print("\n--- COPY THESE NUMBERS INTO YOUR REPORT ---")
print(f"  Average FK Grade Level:  {avg_grade:.1f}")
print(f"  Average Reading Ease:    {avg_ease:.1f}")
print(f"  Age Appropriateness:     {pct_ok:.0f}%")
print("=" * 70 + "\n")
